# Generated by Django 6.0.7 on 2026-07-28 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_trader_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('selected_count', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(default='krx_open_api', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('ticker', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI')], default='KOSPI', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ticker',),
            },
        ),
        migrations.CreateModel(
            name='MarketDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('close_price', models.PositiveBigIntegerField()),
                ('volume', models.PositiveBigIntegerField()),
                ('trading_value', models.PositiveBigIntegerField()),
                ('trading_value_rank', models.PositiveSmallIntegerField()),
                ('source', models.CharField(default='krx_open_api', max_length=30)),
                ('source_payload', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='exchange.symbol')),
            ],
            options={
                'ordering': ('-trade_date', 'trading_value_rank', 'symbol_id'),
                'indexes': [models.Index(fields=['trade_date', 'trading_value_rank'], name='market_daily_date_rank_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'trade_date'), name='unique_symbol_market_daily_trade_date')],
            },
        ),
    ]
